### ISSUE TITLE
Potential use of automatic image resolution for tracking pixel

### ISSUE THREAD

**Issue by sekhat** [LemmyNet/lemmy-ui#1945]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

It's come to my attention (via a mastodon post) that due to Lemmy's automatic loading of image links, that this can pose a privacy issue due to the use "tracking pixels".

See here: https://raddle.me/f/fediverse/166674/lemmy-is-so-much-like-email-it-even-brought-back-spy-tracker

It may be worth looking into solutions to limit this as much as possible.

### Steps to Reproduce

1. Add  an image link to an image on a web server that keeps track of all requests for that image
2. Lemmy will auto load and display this image.
3. Everyone who comes across said image will have their connection and browser details captured.

### Technical Details

This will happen on any web browser on any device.

### Lemmy Instance Version

0.18

**Comment by sekhat** [comment]
Possible solutions I can think of: 

* Have lemmy detect image links, and instead fetch and cache the image server side, for display when the post is rendered, so the image is only ever fetched from the lemmy instance from the users perspective.

Cached, so that it doesn't have to be fetched by the server everytime the post is requested. (Though the cache can drain images that aren't hot, and refetch on demand if not in the cache).

* Display images as links, rather than images. Forcing a user to choose to click on them to see them.

**Comment by lionirdeadman** [comment]
This is a duplicate of https://github.com/LemmyNet/lemmy/issues/2947
